config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('diary.urls', namespace='diary')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diary/urls.py
from django.urls import path

from diary.apps import DiaryConfig
from diary.views import HomeListView, DiaryCreateView, DiaryUpdateView, DiaryDeleteView, DiaryListView, \
    DiaryDetailView, DiaryModerationListView, DiaryModerationActionView

app_name = DiaryConfig.name

urlpatterns = [
    path('', HomeListView.as_view(), name='home'),
    path('moderation/', DiaryModerationListView.as_view(), name='moderation_list'),
    path('moderation/<slug:slug>/action/', DiaryModerationActionView.as_view(), name='moderation_action'),
    path('diary/', DiaryListView.as_view(), name='list'),
    path('create/', DiaryCreateView.as_view(), name='create'),
    path('<slug:slug>/', DiaryDetailView.as_view(), name='detail'),
    path('update/<slug:slug>/', DiaryUpdateView.as_view(), name='update'),
    path('delete/<slug:slug>/', DiaryDeleteView.as_view(), name='delete'),
]

diary/models.py
from django.db import models
from pytils.translit import slugify

from users.models import User, NULLABLE


class Diary(models.Model):
    STATUS_CHOICES = (
        ('no_published', 'Не опубликовано'),
        ('moderation', 'На модерации'),
        ('published', 'Опубликовано'),
        ('rejected', 'Отклонено'),
    )
    title = models.CharField(max_length=100, verbose_name="Заголовок")
    content = models.TextField(verbose_name='Описание')
    slug = models.SlugField(**NULLABLE)
    preview = models.ImageField(upload_to='media/diary/images', verbose_name='Изображение', **NULLABLE)
    created_at = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    views = models.IntegerField(default=0, verbose_name='Просмотры')
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, verbose_name='Владелец', null=True)
    is_published = models.BooleanField(default=False)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='no_published', verbose_name="Статус")

    def __str__(self):
        return f'{self.title} {self.created_at} {self.views}'

    def get_unique_slug(self):
        slug = slugify(self.title)
        unique_slug = slug
        num = 1
        if not self.slug or Diary.objects.filter(slug=unique_slug).exists():
            unique_slug = f"{slug}-{num}"
            num += 1
        return unique_slug

    def save(self, *args, **kwargs):
        self.slug = self.get_unique_slug()
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Дневник'
        verbose_name_plural = 'Дневники'
        ordering = ['-created_at']
        permissions = [
            ('can_moderate', 'Может модерировать записи'),
        ]


class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.SET_NULL, **NULLABLE)
    recipient = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='messages', **NULLABLE)
    name = models.CharField(max_length=200, **NULLABLE)
    email = models.EmailField(max_length=200, **NULLABLE)
    subject = models.CharField(max_length=200, **NULLABLE)
    body = models.TextField()
    is_read = models.BooleanField(default=False, null=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.subject

    class Meta:
        ordering = ['is_read', '-created']
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'

diary/forms.py
from django import forms
from diary.models import Diary
from pytils.translit import slugify


class DiaryForm(forms.ModelForm):
    class Meta:
        model = Diary
        fields = ['title', 'content', 'preview']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 6}),
            'preview': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }

    def save(self, commit=True):
        diary = super().save(commit=False)
        if not diary.slug:
            diary.slug = slugify(diary.title)
        if commit:
            diary.save()
        return diary


class DiaryUpdateForm(forms.ModelForm):
    class Meta:
        model = Diary
        fields = ['title', 'content', 'preview']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите заголовок'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 6, 'placeholder': 'Введите содержание'}),
            'preview': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }

    def save(self, commit=True):
        diary = super().save(commit=False)
        if not diary.slug:
            diary.slug = slugify(diary.title)
        if commit:
            diary.save()
        return diary

diary/views.py
from django.core.exceptions import PermissionDenied
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse_lazy, reverse
from django.utils.html import strip_tags
from django.views import View
from django.views.generic import CreateView, DeleteView, UpdateView, ListView, DetailView
from django.db.models import F, Q
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from config.settings import EMAIL_HOST_USER
from diary.forms import DiaryForm, DiaryUpdateForm
from diary.models import Diary


class HomeListView(ListView):
    """
    Представление для отображения главной страницы с опубликованными записями.
    - queryset: выбираются только записи со статусом is_published=True.
    """
    model = Diary
    template_name = "diary/home.html"
    paginate_by = 10

    def get_queryset(self):
        return Diary.objects.filter(is_published=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Личный дневник'
        return context


class DiaryListView(LoginRequiredMixin, ListView):
    """
    Представление для отображения списка заметок текущего пользователя.
    - queryset: выбираются записи только для владельца (request.user).
    """
    model = Diary
    template_name = 'diary/diary_list.html'
    paginate_by = 10

    def get_queryset(self):
        queryset = Diary.objects.filter(owner=self.request.user)
        query = self.request.GET.get('q')

        if query:
            queryset = queryset.filter(Q(title__icontains=query))

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Список заметок'
        return context


class DiaryDetailView(DetailView):
    """
    Представление для отображения деталей записи.
    - При каждом просмотре запись увеличивает счетчик просмотров.
    - Если просмотров более 100, отправляется уведомление.
    - При POST запросе запись может быть отправлена на модерацию.
    - Опубликованная запись доступна всем пользователям (включая неавторизованных).
    - Неопубликованная запись доступна только владельцу.
    """
    model = Diary
    template_name = 'diary/diary_detail.html'

    def get_object(self, queryset=None):
        """
        Получает объект записи, увеличивает счетчик просмотров,
        если запись опубликована. Если количество просмотров >= 100,
        отправляется уведомление владельцу записи.
        """
        diary = super().get_object(queryset)

        # Проверка доступа
        if not diary.is_published and (self.request.user != diary.owner):
            raise PermissionDenied("У вас нет доступа к этой записи.")

        # Счетчик просмотров только для опубликованных записей
        if diary.is_published:
            Diary.objects.filter(pk=diary.pk).update(views=F('views') + 1)
            diary.refresh_from_db()

        # Уведомление владельцу
        if diary.views >= 100:
            html_message = render_to_string('diary/emails/email_notification.html',
                                            {'title': diary.title})
            plain_message = strip_tags(html_message)

            send_mail(
                subject='Уведомление',
                message=plain_message,
                from_email=EMAIL_HOST_USER,
                recipient_list=[diary.owner.email],
                html_message=html_message
            )
        return diary

    def post(self, request, *args, **kwargs):
        """
        Обрабатывает POST запрос. Если пользователь отправляет запрос на публикацию записи,
        статус записи изменяется на "moderation".
        """
        diary = self.get_object()
        if 'publish' in request.POST:
            diary.status = 'moderation'
            diary.save()
        return redirect('diary:detail', slug=diary.slug)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'О заметке'
        return context


class DiaryCreateView(LoginRequiredMixin, CreateView):
    """
    Представление для создания новой записи.
    - После успешного создания, запись сохраняется за текущим пользователем.
    """
    model = Diary
    form_class = DiaryForm
    success_url = reverse_lazy('diary:list')

    def form_valid(self, form):
        diary = form.save(commit=False)
        diary.owner = self.request.user
        diary.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Новая заметка'
        context['title_h1'] = 'Создать заметку'
        return context


class DiaryUpdateView(LoginRequiredMixin, UpdateView):
    """
    Представление для обновления записи.
    - Пользователь может редактировать только свои записи.
    """
    model = Diary
    form_class = DiaryUpdateForm

    def get_queryset(self):
        return Diary.objects.filter(owner=self.request.user)

    def get_success_url(self):
        return reverse('diary:detail', kwargs={'slug': self.object.slug})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Обновить заметку'
        context['title_h1'] = 'Редактировать заметку'
        return context


class DiaryDeleteView(LoginRequiredMixin, DeleteView):
    """
    Представление для удаления записи.
    - Пользователь может удалить только свои записи.
    - После удаления происходит перенаправление на список записей.
    """
    model = Diary
    success_url = reverse_lazy('diary:list')

    def get_queryset(self):
        return Diary.objects.filter(owner=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Удалить заметку'
        return context


class DiaryModerationListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    """
    Представление для модераторов.
    - Отображает список записей, которые находятся на модерации.
    - Пользователю должна быть выдана соответствующая роль для доступа к этой странице.
    """
    model = Diary
    template_name = 'diary/moderation_list.html'
    permission_required = 'diary.can_moderate'
    paginate_by = 6

    def get_queryset(self):
        return Diary.objects.filter(status='moderation')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Модерация'
        return context


class DiaryModerationActionView(LoginRequiredMixin, PermissionRequiredMixin, View):
    """
    Представление для модераторов.
    - Позволяет утвердить или отклонить запись, отправленную на модерацию.
    - При утверждении запись публикуется, при отклонении — отклоняется.
    """
    permission_required = 'diary.can_moderate'

    def post(self, request, *args, **kwargs):
        diary = get_object_or_404(Diary, slug=kwargs['slug'])

        if 'approve' in request.POST:
            diary.status = 'published'
            diary.is_published = True
            diary.save()
        elif 'reject' in request.POST:
            diary.status = 'rejected'
            diary.save()
        return HttpResponseRedirect(reverse('diary:moderation_list'))

diary/templates/diary/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ title }}</title>
    <!-- Bootstrap для базовых стилей -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Кастомный стиль -->
    <link href="{% static 'css/diary.css' %}" rel="stylesheet">
    <!-- Google Fonts для минималистичных шрифтов -->
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;500&family=Roboto:wght@300;400&display=swap" rel="stylesheet">

</head>
<body>
<div class="diary">
    <!-- Навигационное меню -->
    {% include 'diary/includes/inc_menu.html' %}
    <!-- Основной контент страницы -->
    {% block content %}
    {% endblock %}
<footer>
    <p>&copy; 2024 Личный Дневник. Все права защищены. <a href="#" data-bs-toggle="modal" data-bs-target="#contactModal">Контакты</a></p>
</footer>
</div>
<!-- Модальное окно с контактной информацией -->
<div class="modal fade" id="contactModal" tabindex="-1" aria-labelledby="contactModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="contactModalLabel">Контактная информация</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p><strong>Телефон:</strong> +7 (999) 123-45-67</p>
                <p><strong>Email:</strong> info@personaldiary.ru</p>
                <p><strong>Адрес:</strong> Южно-Сахалинск,ул Пушкина, дом Кукушкина</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
            </div>
        </div>
    </div>
</div>

<!-- Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

diary/templates/diary/diary_confirm_delete.html
{% extends 'diary/base.html' %}
{% block content %}

<style>
    .diary-delete-container {
        background-color: #ffffff;
        border-radius: 8px;
        padding: 30px;
        box-shadow: 0 4px 12px rgba(0, 0, 0, 0.05);
        margin: 50px auto;
        max-width: 600px;
        text-align: center;
    }

    .diary-delete-title {
        font-family: 'Montserrat', sans-serif;
        font-size: 2.5rem;
        font-weight: 500;
        color: #dc3545;
        margin-bottom: 20px;
    }

    .diary-delete-warning {
        font-size: 1.2rem;
        color: #666;
        margin-bottom: 30px;
    }

    .btn-custom {
        background-color: #dc3545;
        border: none;
        color: white;
        padding: 10px 25px;
        border-radius: 50px;
        font-size: 1rem;
        transition: background-color 0.3s ease;
        text-transform: uppercase;
        margin-right: 10px;
    }

    .btn-custom:hover {
        background-color: #bb2d3b;
    }

    .btn-cancel {
        background-color: #6c757d;
    }

    .btn-cancel:hover {
        background-color: #5a6268;
    }

</style>
<div class="diary-delete-container">
    <h1 class="diary-delete-title">Удалить запись</h1>
    <p class="diary-delete-warning">Вы уверены, что хотите удалить эту запись? Это действие не может быть отменено.</p>

    <form method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-custom">Удалить</button>
        <a href="{% url 'diary:list' %}" class="btn btn-cancel">Отмена</a>
    </form>
</div>

{% endblock %}

diary/templates/diary/diary_detail.html
{% extends 'diary/base.html' %}
{% block content %}

<style>
    .diary-detail-container {
        background-color: #ffffff;
        border-radius: 8px;
        padding: 30px;
        box-shadow: 0 4px 12px rgba(0, 0, 0, 0.05);
        margin: 50px auto;
        max-width: 1000px;
        text-align: center;
    }

    .diary-detail-title {
        font-family: 'Montserrat', sans-serif;
        font-size: 2.5rem;
        font-weight: 500;
        color: #087990;
        margin-bottom: 20px;
    }

    .diary-detail-date {
        font-size: 1rem;
        color: #999;
        margin-bottom: 20px;
    }

    .diary-detail-content {
        font-size: 1.2rem;
        color: #555;
        line-height: 1.6;
        font-family: 'Roboto', sans-serif;
        margin-bottom: 30px;
    }

    .diary-detail-preview {
        margin-bottom: 30px;
        max-width: 100%;
        border-radius: 8px;
    }

    .diary-detail-views {
        font-size: 1rem;
        color: #666;
        margin-bottom: 30px;
    }

    .btn-custom {
        background-color: #087990;
        border: none;
        color: white;
        padding: 10px 25px;
        border-radius: 50px;
        font-size: 1rem;
        text-transform: uppercase;
        font-weight: 500;
        font-family: 'Roboto', sans-serif;
        transition: background-color 0.3s ease-in-out;
        margin: 10px 5px;
        display: inline-block;
    }

    .btn-custom:hover {
        background-color: #066c7a;
    }

    .btn-group-custom {
        margin-top: 20px;
    }

    .btn-back {
        margin-top: 30px;
    }
</style>

<div class="diary-detail-container">
    <h1 class="diary-detail-title">{{ object.title }}</h1>
    <p class="diary-detail-date">Создано: {{ object.created_at|date:"d M Y" }}</p>
    {% if object.preview %}
    <img src="{{ object.preview.url }}" alt="Превью записи" class="img-fluid diary-detail-preview">
    {% endif %}
    <div class="diary-detail-content">
        {{ object.content|linebreaks }}
    </div>
    <p class="diary-detail-views">Просмотров: {{ object.views }}</p>
    <p class="diary-detail-status">Статус: {{ object.get_status_display }}</p>
    {% if request.user == object.owner %}
    <div class="btn-back">
        <a href="{% url 'diary:update' slug=object.slug %}" class="btn btn-custom">Редактировать</a>
        <a href="{% url 'diary:delete' slug=object.slug %}" class="btn btn-custom">Удалить</a>
        {% if object.status == 'no_published' %}
        <form method="POST" style="display: inline;">
            {% csrf_token %}
            <button type="submit" name="publish" class="btn btn-custom">Опубликовать</button>
        </form>
        {% endif %}

        <a href="{% url 'diary:list' %}" class="btn btn-custom">Вернуться к списку</a>
    </div>
    {% else %}
    <div class="btn-back">
        {% if user.is_authenticated %}
        <a href="{% url 'diary:list' %}" class="btn btn-custom">Вернуться к списку</a>
        {% else %}
        <a href="/" class="btn btn-custom">Назад</a>
        {% endif %}
    </div>
    {% endif %}
</div>

{% endblock %}

diary/templates/diary/diary_form.html
{% extends 'diary/base.html' %}
{% block content %}

<style>
    .diary-update-container {
        background-color: #ffffff;
        border-radius: 8px;
        padding: 30px;
        box-shadow: 0 4px 12px rgba(0, 0, 0, 0.05);
        margin: 60px auto;
        max-width: 600px;
    }

    .diary-update-title {
        font-family: 'Montserrat', sans-serif;
        font-size: 2.5rem;
        font-weight: 500;
        color: #087990;
        text-align: center;
        margin-bottom: 30px;
    }

    .btn-custom {
        background-color: #087990;
        border: none;
        color: white;
        padding: 10px 25px;
        border-radius: 50px;
        font-size: 1rem;
        transition: background-color 0.3s ease;
        width: 50%;
        text-transform: uppercase;
        margin-left: 140px;
        margin-top: 5px;
    }

    .btn-custom:hover {
        background-color: #066c7a;
    }

    .form-group {
        margin-bottom: 20px;
    }

</style>

<div class="diary-update-container">
    <h1 class="diary-update-title">{{ title_h1 }}</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit" class="btn btn-custom">Сохранить изменения</button>
    </form>
</div>

{% endblock %}

diary/templates/diary/diary_list.html
{% extends 'diary/base.html' %}
{% block content %}

<form method="GET" action="{% url 'diary:list' %}">
    <input type="text" name="q" placeholder="Поиск по заголовкам" value="{{ request.GET.q }}">
    <button type="submit">Поиск</button>
</form>

<section class="diary-section">
    {% if object_list %}
        {% for object in object_list %}
        <div class="diary-entry">
            <h2>{{ object.title|truncatewords:5 }}</h2>
            <p class="entry-date">{{ object.created_at }}</p>
            <p>{{ object.content|truncatewords:50 }}</p>
            <p>Просмотры: {{ object.views }}</p>
            <div class="btn-group-custom">
                <a href="{% url 'diary:detail' slug=object.slug %}" class="btn btn-custom">Подробнее</a>
            </div>
        </div>
        {% endfor %}

        <div class="diary-entry">
            {% if is_paginated %}
            <div class="pagination">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page=1">&laquo; Первая </a>
                        <a href="?page={{ page_obj.previous_page_number }}">Назад</a>
                    {% endif %}

                    <span class="current">
                        Страница {{ page_obj.number }} из {{ paginator.num_pages }}.
                    </span>

                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">Следующая</a>
                        <a href="?page={{ paginator.num_pages }}">Последняя &raquo;</a>
                    {% endif %}
                </span>
            </div>
            {% endif %}
        </div>
    {% else %}
        <div class="modal fade" id="noResultsModal" tabindex="-1" aria-labelledby="noResultsModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="noResultsModalLabel">Поиск</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        К сожалению, по вашему запросу ничего не найдено.
                    </div>
                    <div class="modal-footer">
                        <a href="{% url 'diary:list' %}" class="btn btn-secondary">Закрыть</a>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
</section>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>

{% if not object_list %}
<script>
    var myModal = new bootstrap.Modal(document.getElementById('noResultsModal'));
    myModal.show();
</script>
{% endif %}
{% endblock %}

diary/templates/diary/home.html
{% extends 'diary/base.html' %}
{% block content %}

<header>
    <h1>Личный Дневник</h1>
    <p>Записывайте свои мысли и воспоминания в светлом и уютном стиле.</p>
</header>
<section class="diary-section">
        {% for object in object_list %}
        <div class="diary-entry">
            <h2>{{ object.title|truncatewords:5 }}</h2>
            <p class="entry-date">{{ object.created_at }}</p>
            <p>{{ object.content|truncatewords:50 }}</p>
            <p>Просмотры: {{ object.views }}</p>
            <div class="btn-group-custom">
                <a href="{% url 'diary:detail' slug=object.slug %}" class="btn btn-custom">Подробнее</a>
            </div>
        </div>
        {% endfor %}
</section>

{% endblock %}

diary/templates/diary/moderation_list.html
{% extends 'diary/base.html' %}
{% block content %}

<style>
    .diary-detail-container {
        background-color: #ffffff;
        border-radius: 8px;
        padding: 30px;
        box-shadow: 0 4px 12px rgba(0, 0, 0, 0.05);
        margin: 50px auto;
        max-width: 1000px;
        text-align: center;
    }

    .diary-detail-title {
        font-family: 'Montserrat', sans-serif;
        font-size: 2.5rem;
        font-weight: 500;
        color: #087990;
        margin-bottom: 20px;
    }

    .diary-detail-date {
        font-size: 1rem;
        color: #999;
        margin-bottom: 20px;
    }

    .diary-detail-content {
        font-size: 1.2rem;
        color: #555;
        line-height: 1.6;
        font-family: 'Roboto', sans-serif;
        margin-bottom: 30px;
    }

    .btn-custom {
        background-color: #087990;
        border: none;
        color: white;
        padding: 10px 25px;
        border-radius: 50px;
        font-size: 1rem;
        text-transform: uppercase;
        font-weight: 500;
        font-family: 'Roboto', sans-serif;
        transition: background-color 0.3s ease-in-out;
        margin: 10px 5px;
        display: inline-block;
    }

    .btn-custom:hover {
        background-color: #066c7a;
    }

    .btn-group-custom {
        margin-top: 20px;
    }

    .modal-content {
        padding: 20px;
        border-radius: 10px;
    }
</style>

<div class="container">
    <div class="diary-section row">
        {% for diary in object_list %}
        <div class="diary-entry col-md-4 mb-4">
            <h2>{{ diary.title|truncatewords:5 }}</h2>
            <p class="entry-date">{{ diary.created_at|date:"d M Y" }}</p>
            <button class="btn btn-custom" data-bs-toggle="modal" data-bs-target="#diaryModal{{ diary.pk }}">
                Подробнее
            </button>
        </div>

        <!-- Модальное окно -->
        <div class="modal fade" id="diaryModal{{ diary.pk }}" tabindex="-1" aria-labelledby="diaryModalLabel{{ diary.pk }}" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="diaryModalLabel{{ diary.pk }}">{{ diary.title }}</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <p class="diary-detail-date">Создано: {{ diary.created_at|date:"d M Y" }}</p>
                        <p>{{ diary.content }}</p>
                    </div>
                    <div class="modal-footer">
                        <form method="post" action="{% url 'diary:moderation_action' diary.slug %}">
                            {% csrf_token %}
                            <button type="submit" name="approve" class="btn btn-custom">Опубликовать</button>
                            <button type="submit" name="reject" class="btn btn-custom">Отклонить</button>
                        </form>
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        <div class="diary-entry">
    {% if is_paginated %}
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; Первая </a>
                <a href="?page={{ page_obj.previous_page_number }}">Назад</a>
            {% endif %}

            <span class="current">
                Страница {{ page_obj.number }} из {{ paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">Следующая</a>
                <a href="?page={{ paginator.num_pages }}">Последняя &raquo;</a>
            {% endif %}
        </span>
    </div>
    {% endif %}
    </div>
    </div>
</div>

{% endblock %}